# SPDX-FileCopyrightText: 2025 Scarlett Moore <sgmoore@kde.org>
# SPDX-FileCopyrightText: 2025 Carlos De Maine <carlosd.kde@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: glaxnimate
base: core24
adopt-info: glaxnimate
grade: stable
confinement: strict

apps:
  glaxnimate:
    command: usr/bin/glaxnimate
    common-id: org.kde.glaxnimate.desktop
    desktop: usr/share/applications/org.kde.glaxnimate.desktop
    extensions:
      - kde-neon-6
    plugs:
      - audio-playback
      - home
      - unity7
    environment:
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy${LD_LIBRARY_PATH}
      PATH: $SNAP/ffmpeg-platform/usr/bin:$SNAP/usr/bin${PATH}
      ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
      QT_MEDIA_BACKEND: "ffmpeg"
      XDG_DATA_DIRS: "$XDG_DATA_DIRS:$SNAP/usr/share"
      XDG_CONFIG_DIRS: "$XDG_CONFIG_DIRS:$SNAP/etc/xdg"

plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform # the folder where this content snap will be mounted
    default-provider: ffmpeg-2404

parts:
  glaxnimate:
    parse-info:
      - usr/share/metainfo/org.kde.glaxnimate.metainfo.xml
    plugin: cmake
    source: .
    source-type: local
    cmake-parameters:
      - -DBUILD_TESTING=OFF
      - -DBUILD_WITH_QT6=ON
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
      - -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON
      - -DCMAKE_FIND_ROOT_PATH="/snap/ffmpeg-2404-sdk/current;/snap/kde-qt6-core24-sdk/current;/snap/kf6-core24-sdk/current"
      - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -DCMAKE_INSTALL_LOCALSTATEDIR=/var
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_RUNSTATEDIR=/run
      - -DCMAKE_INSTALL_SYSCONFDIR=/etc
      - -DCMAKE_LIBRARY_PATH=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON
      - -DCMAKE_VERBOSE_MAKEFILE=ON
      - -DQT_MAJOR_VERSION=6
      - --log-level=STATUS
    build-environment:
      - CMAKE_FIND_ROOT_PATH: "${CMAKE_FIND_ROOT_PATH}:/snap/ffmpeg-2404-sdk/current"
      - PKG_CONFIG_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig"
      - LD_LIBRARY_PATH: "/snap/mesa-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
    build-packages:
      - libarchive-dev
      - libpotrace-dev
      - libpython3-dev
      - libswscale-dev
      - pybind11-dev
      - zlib1g-dev
    build-snaps:
      - ffmpeg-2404-sdk
    stage-packages:
      - libarchive13t64
      - libpotrace0
      - libarchive13t64
      - python3-pybind11
      - zlib1g
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [glaxnimate]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - glaxnimate
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done

